export const LOGIN_SITE = "LOGIN_SITE";
export const LOGOUT_SITE = "LOGOUT_SITE";
export const LOGIN_SITE_CANCELLED = "LOGIN_SITE_CANCELLED";
export const LOGIN_SITE_SUCCESS = "LOGIN_SITE_SUCCESS";
export const LOGIN_SITE_FAIL = "LOGIN_SITE_FAIL";
