export const USER_AUTH_CHECK = "USER_AUTH_CHECK";
export const CLEAR_EXPIRED_TOKEN = "CLEAR_EXPIRED_TOKEN";
export const LOGIN_SITE = "LOGIN_SITE";
export const LOGOUT_SITE = "LOGOUT_SITE";
export const LOGIN_SITE_CANCELLED = "LOGIN_SITE_CANCELLED";
export const SET_USER_STATE = "SET_USER_STATE";
export const LOGIN_SITE_FAIL = "LOGIN_SITE_FAIL";
